#!/bin/bash
# Generated by skillport — preprocessor for dynamic context
# Run before launching Codex to inject live data

SKILL_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SKILL_FILE="$SKILL_DIR/SKILL.md"

RESULT=$(cmd 2>/dev/null || echo "[command failed]")
sed -i '' "s|!`cmd`|$RESULT|g" "$SKILL_FILE"

RESULT=$(cmd 2>/dev/null || echo "[command failed]")
sed -i '' "s|!`cmd`|$RESULT|g" "$SKILL_FILE"

echo "Dynamic context rendered for Codex"