#!/bin/bash
# Generated by skillport — renders dynamic context placeholders
# Run this before first use to inject live data into the skill

SKILL_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SKILL_FILE="$SKILL_DIR/SKILL.md"

# Evaluate: !`cmd`
RESULT=$(cmd 2>/dev/null || echo "[command failed]")
sed -i '' "s|!`cmd`|$RESULT|g" "$SKILL_FILE"

# Evaluate: !`cmd`
RESULT=$(cmd 2>/dev/null || echo "[command failed]")
sed -i '' "s|!`cmd`|$RESULT|g" "$SKILL_FILE"

echo "Dynamic context rendered successfully"